# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CardPayment' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CardPayment
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'ObjectMapper'
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'

  target 'CardPaymentTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CardPaymentUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
